services:
  generatetemplate.application:
    image: ${DOCKER_REGISTRY-}generatetemplateapplication
    build:
      context: .
      dockerfile: Dockerfile
    container_name: generatetempla_application
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionString=mongodb://mongodb_container:27017 
      - ASPNETCORE_URLS=http://+:80
      - EnableSwaggerSupport=true
      - Redis__ConnectionString=redis:6379
    ports:
      - "8080:80"
    networks:
      - app_network
      
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - app_network
      
  redis: 
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
